"""Add student_name and student_id to Evaluation model

Revision ID: 5e7ee60ea0c4
Revises: 
Create Date: 2024-07-11 19:25:52.192295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7ee60ea0c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_column('student_id')
        batch_op.drop_column('student_name')

    # ### end Alembic commands ###
